export const config = {
  automaticRearrangeAfterDropNode: true,
  collapsible: false,
  directed: false,
  focusAnimationDuration: 0.75,
  focusZoom: 3,
  freezeAllDragEvents: false,
  highlightDegree: 2,
  highlightOpacity: 0.2,
  linkHighlightBehavior: true,
  maxZoom: 12,
  minZoom: 1.25,
  nodeHighlightBehavior: true,
  panAndZoom: false,
  staticGraph: false,
  staticGraphWithDragAndDrop: false,
  d3: {
    alphaTarget: 0.05,
    gravity: -600,
    linkLength: 120,
    linkStrength: 2,
    disableLinkForce: false,
  },
  node: {
    color: '#C5CAE9',
    fontColor: 'black',
    fontSize: 10,
    fontWeight: 'bold',
    highlightColor: '#2962ff',
    highlightFontSize: 10,
    highlightFontWeight: 'bold',
    highlightStrokeColor: '#2962ff',
    highlightStrokeWidth: 1,
    mouseCursor: 'crosshair',
    opacity: 0.9,
    renderLabel: true,
    size: 100,
    strokeColor: 'none',
    symbolType: 'circle',
  },
  link: {
    color: '#C5CAE9',
    fontColor: 'black',
    fontSize: 8,
    fontWeight: 'normal',
    highlightColor: '#2962ff',
    highlightFontSize: 8,
    highlightFontWeight: 'normal',
    mouseCursor: 'pointer',
    opacity: 1,
    renderLabel: false,
    semanticStrokeWidth: true,
    strokeWidth: 1.5,
    markerHeight: 4,
    markerWidth: 4,
  },
};
