import { upperCase } from 'lodash';

export const config = {
  automaticRearrangeAfterDropNode: false,
  collapsible: false,
  directed: false,
  focusAnimationDuration: 0.75,
  focusZoom: 1,
  freezeAllDragEvents: false,
  highlightDegree: 1,
  highlightOpacity: 0.2,
  linkHighlightBehavior: true,
  maxZoom: 12,
  minZoom: 0.05,
  nodeHighlightBehavior: true,
  panAndZoom: false,
  staticGraph: false,
  staticGraphWithDragAndDrop: false,
  d3: {
    alphaTarget: 0.05,
    gravity: -400,
    linkLength: 100,
    linkStrength: 1,
    disableLinkForce: false,
  },
  node: {
    color: '#C5CAE9',
    fontColor: 'black',
    fontSize: 10,
    fontWeight: 'bold',
    highlightColor: '#2962FF',
    highlightFontSize: 10,
    highlightFontWeight: 'bold',
    highlightStrokeColor: '#2962FF',
    highlightStrokeWidth: 1.5,
    mouseCursor: 'crosshair',
    opacity: 0.9,
    renderLabel: true,
    size: 200,
    strokeColor: 'none',
    strokeWidth: 1.5,
    svg: '',
    symbolType: 'circle',
    labelProperty: ({ id }: any) => upperCase(id),
  },
  link: {
    color: '#C5CAE9',
    fontColor: 'black',
    fontSize: 8,
    fontWeight: 'normal',
    highlightColor: 'default',
    highlightFontSize: 8,
    highlightFontWeight: 'normal',
    mouseCursor: 'pointer',
    opacity: 1,
    renderLabel: false,
    semanticStrokeWidth: true,
    strokeWidth: 2,
    markerHeight: 6,
    markerWidth: 6,
    strokeDasharray: 0,
    strokeDashoffset: 0,
    strokeLinecap: 'butt',
  },
};
